import { Subject, Resource, UserPreferences, MockTest, Habit } from '@/store/useGateStore';

export const DEFAULT_SUBJECTS: Subject[] = [
  {
    id: 'aptitude',
    name: 'General Aptitude',
    weightage: 'high',
    approxMarks: 15,
    dependencies: [],
    status: 'in_progress',
    totalPYQs: 150,
    solvedPYQs: 10,
    pyqAccuracy: 80,
    revisionProgress: 0,
  },
  {
    id: 'engineering-math',
    name: 'Engineering Mathematics',
    weightage: 'high',
    approxMarks: 13,
    dependencies: [],
    status: 'ready',
    totalPYQs: 120,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'discrete-math',
    name: 'Discrete Mathematics',
    weightage: 'high',
    approxMarks: 7,
    dependencies: ['engineering-math'],
    status: 'locked',
    totalPYQs: 110,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'digital-logic',
    name: 'Digital Logic',
    weightage: 'medium',
    approxMarks: 5,
    dependencies: [],
    status: 'ready',
    totalPYQs: 90,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'coa',
    name: 'Computer Organization & Architecture (COA)',
    weightage: 'medium',
    approxMarks: 6,
    dependencies: ['digital-logic'],
    status: 'locked',
    totalPYQs: 100,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'c-programming',
    name: 'C Programming',
    weightage: 'high',
    approxMarks: 4,
    dependencies: [],
    status: 'ready',
    totalPYQs: 80,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'data-structures',
    name: 'Data Structures',
    weightage: 'high',
    approxMarks: 6,
    dependencies: ['c-programming'],
    status: 'locked',
    totalPYQs: 100,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'algorithms',
    name: 'Algorithms',
    weightage: 'high',
    approxMarks: 7,
    dependencies: ['data-structures'],
    status: 'locked',
    totalPYQs: 120,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'operating-systems',
    name: 'Operating Systems',
    weightage: 'high',
    approxMarks: 8,
    dependencies: ['c-programming'],
    status: 'locked',
    totalPYQs: 110,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'dbms',
    name: 'Database Management Systems (DBMS)',
    weightage: 'high',
    approxMarks: 8,
    dependencies: ['operating-systems'],
    status: 'locked',
    totalPYQs: 100,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'computer-networks',
    name: 'Computer Networks',
    weightage: 'high',
    approxMarks: 9,
    dependencies: ['operating-systems'],
    status: 'locked',
    totalPYQs: 130,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'toc',
    name: 'Theory of Computation',
    weightage: 'high',
    approxMarks: 8,
    dependencies: ['discrete-math'],
    status: 'locked',
    totalPYQs: 120,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
  {
    id: 'compiler-design',
    name: 'Compiler Design',
    weightage: 'medium',
    approxMarks: 4,
    dependencies: ['toc'],
    status: 'locked',
    totalPYQs: 80,
    solvedPYQs: 0,
    pyqAccuracy: 0,
    revisionProgress: 0,
  },
];

export const DEFAULT_RESOURCES: Resource[] = [
  {
    id: 'r_aptitude',
    subjectId: 'aptitude',
    name: 'General Aptitude Lectures by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PLvTTv60o7qj9YJU93vxkf570EQOfPnhwP',
    priority: 'high',
    difficulty: 'easy',
    status: 'in_progress',
    totalVideos: 60,
    completedVideos: 10,
    totalDuration: 30,
    completedDuration: 5,
    avgVideoDuration: 30,
  },
  {
    id: 'r_math',
    subjectId: 'engineering-math',
    name: 'Engineering Mathematics by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PLvTTv60o7qj_tdY9zH7YceES7jfXiZkAz',
    priority: 'high',
    difficulty: 'medium',
    status: 'not_started',
    totalVideos: 80,
    completedVideos: 0,
    totalDuration: 45,
    completedDuration: 0,
    avgVideoDuration: 34,
  },
  {
    id: 'r_discrete',
    subjectId: 'discrete-math',
    name: 'Discrete Mathematics by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH9TTRzwOcwbXtUVK8-NHZrJ',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 120,
    completedVideos: 0,
    totalDuration: 70,
    completedDuration: 0,
    avgVideoDuration: 35,
  },
  {
    id: 'r_c',
    subjectId: 'c-programming',
    name: 'C Programming by Neso Academy',
    type: 'youtube_playlist',
    instructor: 'Neso Academy',
    link: 'https://youtube.com/playlist?list=PLbE3-5DBkMUkATaUFgDIpBDbfnym0qvsQ',
    priority: 'high',
    difficulty: 'easy',
    status: 'not_started',
    totalVideos: 60,
    completedVideos: 0,
    totalDuration: 25,
    completedDuration: 0,
    avgVideoDuration: 25,
  },
  {
    id: 'r_digital',
    subjectId: 'digital-logic',
    name: 'Digital Electronics by Sanchit Jain',
    type: 'youtube_playlist',
    instructor: 'Knowledge Gate (Sanchit Jain)',
    link: 'https://youtube.com/playlist?list=PLEBuowGoCtr0jQwu937nDiABSVbC_Lsp5',
    priority: 'high',
    difficulty: 'medium',
    status: 'not_started',
    totalVideos: 60,
    completedVideos: 0,
    totalDuration: 22,
    completedDuration: 0,
    avgVideoDuration: 22,
  },
  {
    id: 'r_ds',
    subjectId: 'data-structures',
    name: 'Data Structures by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH-D-X8940NKo0ouhK0Mg-hf',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 80,
    completedVideos: 0,
    totalDuration: 40,
    completedDuration: 0,
    avgVideoDuration: 30,
  },
  {
    id: 'r_algo',
    subjectId: 'algorithms',
    name: 'Algorithms by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH87NTeUU8AteQQ7cmO33gOY',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 70,
    completedVideos: 0,
    totalDuration: 38,
    completedDuration: 0,
    avgVideoDuration: 32,
  },
  {
    id: 'r_toc',
    subjectId: 'toc',
    name: 'Theory of Computation by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH_ePbZWc1nKZuyfru6sgioD',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 110,
    completedVideos: 0,
    totalDuration: 65,
    completedDuration: 0,
    avgVideoDuration: 35,
  },
  {
    id: 'r_coa',
    subjectId: 'coa',
    name: 'COA by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH87OmcXOZYS40CqjWYeT1S3',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 75,
    completedVideos: 0,
    totalDuration: 42,
    completedDuration: 0,
    avgVideoDuration: 33,
  },
  {
    id: 'r_os',
    subjectId: 'operating-systems',
    name: 'Operating Systems by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH8VzPps-6bxQUhwZ0MnYqTT',
    priority: 'high',
    difficulty: 'medium',
    status: 'not_started',
    totalVideos: 105,
    completedVideos: 0,
    totalDuration: 60,
    completedDuration: 0,
    avgVideoDuration: 34,
  },
  {
    id: 'r_dbms',
    subjectId: 'dbms',
    name: 'DBMS by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH8y4nMdFH27hbDBsSxoJnV_',
    priority: 'high',
    difficulty: 'medium',
    status: 'not_started',
    totalVideos: 95,
    completedVideos: 0,
    totalDuration: 55,
    completedDuration: 0,
    avgVideoDuration: 35,
  },
  {
    id: 'r_cn',
    subjectId: 'computer-networks',
    name: 'Computer Networks by Amit Khurana',
    type: 'youtube_playlist',
    instructor: 'Amit Khurana',
    link: 'https://youtube.com/playlist?list=PL3eEXnCBViH-hlNCNwdfV7VrEcTquANGa',
    priority: 'high',
    difficulty: 'hard',
    status: 'not_started',
    totalVideos: 100,
    completedVideos: 0,
    totalDuration: 58,
    completedDuration: 0,
    avgVideoDuration: 35,
  },
  {
    id: 'r_cd',
    subjectId: 'compiler-design',
    name: 'Compiler Design by Gate Smashers',
    type: 'youtube_playlist',
    instructor: 'Gate Smashers',
    link: 'https://youtube.com/playlist?list=PLLOG_8OlGMp70Qy_dOSXNFFuyNqKHeMVej',
    priority: 'high',
    difficulty: 'medium',
    status: 'not_started',
    totalVideos: 30,
    completedVideos: 0,
    totalDuration: 15,
    completedDuration: 0,
    avgVideoDuration: 30,
  },
  {
    id: 'r_pyq_practice',
    subjectId: 'algorithms',
    name: 'Practice Paper Topic-Wise GATE CSE PYQs',
    type: 'notes',
    instructor: 'PracticePaper.in',
    link: 'https://practicepaper.in/gate-cse/topic-wise-practice-of-gate-cse-previous-year-papers',
    priority: 'high',
    difficulty: 'medium',
    status: 'in_progress',
  }
];

export const DEFAULT_PREFERENCES: UserPreferences = {
  gateDate: '2027-02-06',
  startDate: new Date().toISOString().split('T')[0],
  dailyStudyHours: 4,
  weeklyOffDays: 1,
  playbackSpeed: 1.5,
  revisionCycles: 3,
  mockTestFrequency: 'weekly',
};

export const DEFAULT_MOCK_TESTS: MockTest[] = [
  {
    id: 'mt1',
    name: 'GATE Full Length Mock 1',
    date: '2026-06-10',
    score: 42.5,
    rank: 1250,
    accuracy: 65,
  },
  {
    id: 'mt2',
    name: 'GATE Subject Test - C & DS',
    date: '2026-06-18',
    score: 62.0,
    rank: 450,
    accuracy: 78,
  },
  {
    id: 'mt3',
    name: 'GATE Full Length Mock 2',
    date: '2026-06-24',
    score: 55.0,
    rank: 820,
    accuracy: 72,
  },
];

export const DEFAULT_HABITS: Habit[] = [
  {
    id: 'h1',
    name: 'Solve 10 PYQs',
    completedDates: [],
    streak: 0,
  },
  {
    id: 'h2',
    name: 'Study 4 Hours',
    completedDates: [],
    streak: 0,
  },
  {
    id: 'h3',
    name: 'Active Revision Session',
    completedDates: [],
    streak: 0,
  },
];
